name: GitHub Actions Demo
run-name: paks teszt
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - run: |
          ( date -u '+%Y.%m.%d %H:%M' ; curl https://atomeromu.mvm.hu/ -k -s | sed -n 's|^.*dominant-baseline[^>]*>\([0-9\.]*\)<.*$|\1|p' | head -4 | tr '.' ',' ) | tr '\r\n' ';' | rev | cut -c 2- | rev >> paks.csv
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update"
          git push
