name: GitHub Actions Demo
run-name: ${{ github.actor }} paks teszt
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ( date -u -Iminutes ; curl https://atomeromu.mvm.hu/ -k -s | sed -n 's|^.*dominant-baseline[^>]*>\([0-9\.]*\)<.*$|\1|p' | head -4 ) | tr '\r\n' ',' >> paks.csv
      - run: cat paks.csv
